### ISSUE TITLE
files are growing

### ISSUE THREAD

**Issue by SimonDanisch** [domluna/JuliaFormatter.jl#321]
After executing `format(".")`  lots of times to find bugs, I noticed that formatting slowed down a lot. I was quite puzzled, until my OS warned me, that disk space was getting low. Turns out, 2 files were growing to 10gb. After resetting the files, they seem to behave well now. So, not really sure what happened here. If it happens again, I'll try to find some more information.

**Comment by SimonDanisch** [comment]
By the way, all of these bugs come from running `format(".")` in `AbstractPlotting.jl` if you want a good test code base ;)

The .JuliaFormatter.toml:
```toml
always_for_in = true
always_use_return = true
import_to_using = true
margin = 110
pipe_to_function_call = true
remove_extra_newlines = true
short_to_long_function_def = true
style = "yas"
whitespace_in_kwargs = false
whitespace_ops_in_indices = true
whitespace_typedefs = false
```
