### ISSUE TITLE
JuliaFormatter converts regular to keyword arguments

### ISSUE THREAD

**Issue by eschnett** [domluna/JuliaFormatter.jl#533]
I find that JuliaFormatter converts
```Julia
function linterp(x0::T, y0::T, x1::T, y1::T, x::T, extrap::Bool=false)::T where {T<:AbstractFloat}
```
to
```Julia
function linterp(x0::T, y0::T, x1::T, y1::T, x::T; extrap::Bool=false)::T where {T<:AbstractFloat}
```
That is, the regular argument `extrap` is converted to a keyword argument. (This breaks the code.)

The source code is [here](https://gist.github.com/eschnett/033651ab916979a433a0cc1cf7982c20).

I am using JuliaFormatter v0.21.1 on Julia 1.7.1.

My `~/.JuliaFormatter.toml` file is
```toml
style = "yas"
indent = 4
margin = 132
always_for_in = true
whitespace_ops_in_indices = true
whitespace_typedefs = false
remove_extra_newlines = true
import_to_using = true
pipe_to_function_call = true
short_to_long_function_def = true
always_use_return = true
```
