### ISSUE TITLE
Empty style for strictly opt-in functionality

### ISSUE THREAD

**Issue by fredrikekre** [domluna/JuliaFormatter.jl#561]
Is there a way to configure JuliaFormatter to only do things I specify? I am thinking of something like an "empty" style which makes every change opt-in. Example config
```toml
style = "nothing"
always_for_in = true
```
which would *only* change `=` to `in`, but nothing else.
