### ISSUE TITLE
Add option to ignore files matching patterns

### ISSUE THREAD

**Issue by chriselrod** [domluna/JuliaFormatter.jl#574]
It alw
```julia
julia> format(".")
ERROR: SystemError: opening file "src/.#fileiameditting.jl": No such file or directory
```

**Comment by stemann** [comment]
Could be relevant wrt. GitLab CI as well, where GitLab CI forces the user to stick `.julia` (i.e. `JULIA_DEPOT_PATH`) in the project directory to enable caching between CI jobs, and then one needs to temporarily move `./.julia` out of that way, and update `JULIA_DEPOT_PATH`, before running `format(".")`:

```yaml
include:
  - project: 'ihp/julia/julia-gitlab-ci-templates'
    ref: v1.2.0
    file: '/templates.gitlab-ci.yaml' # This sets JULIA_DEPOT_PATH - for caching purposes - which might also be nice wrt. to caching JuliaFormatter install

format:
  extends:
    - .julia.setup
  stage: test
  script:
    - "[[ -d .julia ]] && mv .julia /tmp"
    - |
      julia --eval '
        using Pkg
        Pkg.add("JuliaFormatter")
        using JuliaFormatter
        not_formatted = format(pwd(); verbose = true)
        if not_formatted
          @info "Formatting verified."
        else
          @warn "Formatting verification failed: Some files are not properly formatted!"
        end
        exit(not_formatted ? 0 : 1)
      '
    - "[[ -d /tmp/.julia ]] && mv /tmp/.julia ."
  variables:
    CI_JULIA_VERSION: "1.7"
    JULIA_DEPOT_PATH: /tmp/.julia
```
The snippet above is based on: https://github.com/IHPSystems/julia-gitlab-ci-templates/blob/v1.2.0/templates.gitlab-ci.yaml (alias https://gitlab.com/IHPSystems/julia/julia-gitlab-ci-templates/-/blob/v1.2.0/templates.gitlab-ci.yaml )
