### ISSUE TITLE
`format` not idempotent, sometimes breaks code

### ISSUE THREAD

**Issue by cscherrer** [domluna/JuliaFormatter.jl#579]
It seems desirable for `format` to be "idempotent" - that is, calling it twice should be no different than calling it once. I found a strange example where this is not the case.

Original:
```julia
import MeasureTheory.:⋅ 

function ⋅(μ::Normal, kernel)
    m = kernel(μ)
    Normal(μ = m.μ.μ, σ = sqrt(m.μ.σ^2 + m.σ^2))
end
```

After `format`:
```julia
import MeasureTheory.: ⋅
function ⋅(μ::Normal, kernel)
    m = kernel(μ)
    Normal(μ = m.μ.μ, σ = sqrt(m.μ.σ^2 + m.σ^2))
end
```

After a second `format`:
```julia
import MeasureTheory.: ⋅ function ⋅(μ::Normal, kernel)
    m = kernel(μ)
    Normal(μ = m.μ.μ, σ = sqrt(m.μ.σ^2 + m.σ^2))
end
```

This last one is especially concerning, because it's not valid Julia.

This is in JuliaFormatter v0.22.10. My `.JuliaFormatter.toml` file looks like this:
```toml
indent = 4
margin = 92
always_for_in = true
whitespace_typedefs = false
whitespace_ops_in_indices = false
remove_extra_newlines = true
import_to_using = false
pipe_to_function_call = false
short_to_long_function_def = true
always_use_return = false
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = false
format_docstrings = false
align_struct_field = true
align_conditional = true
align_assignment = true
align_pair_arrow = true
conditional_to_if = true
normalize_line_endings = "unix"
align_matrix = false
```
