### ISSUE TITLE
short to long functions with begin end blocks

### ISSUE THREAD

**Issue by untoreh** [domluna/JuliaFormatter.jl#686]
Short functions written like:
```julia
abc() = begin
    1
end
```
are rewritten to:
```julia
function abc()
    begin
    1
    end
end
```
The outer `begin ... end` block should be elided

myconf:
```toml
style="blue"
margin=92
always_use_return=false
remove_extra_newlines=true
overwrite=false
pipe_to_function_call=false
```
