### ISSUE TITLE
let functions rewrite to invalid syntax

### ISSUE THREAD

**Issue by untoreh** [domluna/JuliaFormatter.jl#698]
```julia
let hello() = begin
        print("ok")
    end
    hello()
end

let hello() = print("ok");
    hello()
end
```
get rewritten to
```julia
let function hello()
        print(
            "ok",
        )
    end
    hello()
end
```

config
```toml
style="blue"
margin=10
always_use_return=false
remove_extra_newlines=true
overwrite=false
pipe_to_function_call=false
```
