### ISSUE TITLE
Consider allowing an argument to the pre-commit hook to give the project

### ISSUE THREAD

**Issue by abelsiqueira** [domluna/JuliaFormatter.jl#842]
This line:

https://github.com/domluna/JuliaFormatter.jl/blob/0208ed4ea5b4d313ed4a0dc322c4334185bd487f/.pre-commit-hooks.yaml#L3

Could be changed to include `--project=X` where X is some argument to the pre-commit hook. It would allow people that install JuliaFormatter on a separate global environment.

**Comment by m-fila** [comment]
This can be done already by specifying `args` in your `pre-commit-config.yaml`. For instance
```
repos:
  - repo: https://github.com/domluna/JuliaFormatter.jl.git
    rev: v1.0.56
    hooks:
    -   id: "julia-formatter"
        args: [--project=/tmp/X]
```
