### ISSUE TITLE
How to integrate JuliaFormatter with Helix

### ISSUE THREAD

**Issue by arunoruto** [domluna/JuliaFormatter.jl#868]
I am currently using [helix](https://helix-editor.com/) as my main "IDE" and I wanted to use it for Julia too. Configuring a formatter in helix is really straight forward: the contents will be passed to a command as stdin and the output is expected on stdout, as explained in [this](https://github.com/helix-editor/helix/discussions/11510) discussion. There are example in the README.md for formatting folders recursively and files. It would be nice if an example for stdin and stdout would be provided, if possible. If not, adding this feature would benefit. An example for an abstract language is also provided [here](https://docs.helix-editor.com/languages.html#language-configuration) by helix.

**Comment by arunoruto** [comment]
Well, after digging more into this (I am a bit new to Julia and its ecosystem), I found a suitable solution!
The following configuration of helix works for me:
```toml
[[language]]
name = "julia"
...

[language.formatter]
args = ["--startup-file=no", "--history-file=no", "--quiet", "-e", "using JuliaFormatter; println(format_text(join(readlines(stdin), '\\n')))"]
command = "julia"
```

This will work for now, but it is a bit slowish. I am not sure if I am doing something wrong, so if there is a better/faster way, I am eager to learn it :)

I will keep the issue open for now, but if no one replies to it, I will close it.
