### ISSUE TITLE
Closing bracket not indented properly

### ISSUE THREAD

**Issue by arlowhite** [domluna/JuliaFormatter.jl#876]
We have this code where the closing bracket `]` is not indented properly.

### Original Code
```julia
function find_horizontal(geom::GIWrap.Polygon)::Vector{Tuple{Float64,Float64}}
    coords = collect(GI.coordinates(geom)...)
    first_coord = first(coords)
    second_coord = coords[
        (getindex.(coords, 2) .∈ first_coord[2]) .&&
        (getindex.(coords, 1) .∉ first_coord[1])
    ]

    return [tuple(first_coord...), tuple(first(second_coord)...)]
end
```

### Formatted
```julia
function find_horizontal(geom::GIWrap.Polygon)::Vector{Tuple{Float64,Float64}}
    coords = collect(GI.coordinates(geom)...)
    first_coord = first(coords)
    second_coord = coords[
    (getindex.(coords, 2) .∈ first_coord[2]) .&& (getindex.(coords, 1) .∉ first_coord[1])
]

    return [tuple(first_coord...), tuple(first(second_coord)...)]
end
```

### Expected

I prefer the original code, but would expect the indents to look like this after format:
```julia
    second_coord = coords[
        (getindex.(coords, 2) .∈ first_coord[2]) .&& (getindex.(coords, 1) .∉ first_coord[1])
    ]
```

## .JuliaFormatter.toml

```toml
style="blue"
indent=4
margin=92
always_for_in="nothing"
for_in_replacement="∈"
whitespace_typedefs=false
import_to_using=true
align_struct_field=true
align_assignment=false
align_conditional=true
align_pair_arrow=false
normalize_line_endings="unix"
align_matrix=true
join_lines_based_on_source=true
indent_submodule=true
surround_whereop_typeparameters=false
yas_style_nesting=true
trailing_comma=false
short_to_long_function_def=false
conditional_to_if=false
```
